GetPermissions
s21platform/society-service pull request #12
Opened 2024-11-12 16:08 UTC by lalankos

Added GetPermissions

2024-11-14 23:38 UTC, alexseipopov requested changes

2024-11-14 23:38 UTC, alexseipopov commented on internal/model/society.go
> +type GetPermissionsData struct {
Эту структурку можно не создавать. См коммент repository.go

2024-11-14 23:38 UTC, alexseipopov commented on internal/repository/postgres/repository.go
> +	getData := model.GetPermissionsData{}
тут можно создать data :=  []model.GetPermission

2024-11-14 23:38 UTC, alexseipopov commented on internal/repository/postgres/repository.go
> +	err := r.connection.Select(&getData.GetPermissions, "SELECT id, name, description FROM user_permissions")
тут соответственно будет &data

2024-11-14 23:38 UTC, alexseipopov commented on internal/repository/postgres/repository.go
> +	return &getData, nil
Тут соответсвенно return data, nil

2024-11-14 23:38 UTC, alexseipopov commented on internal/repository/postgres/repository.go
> +		return nil, fmt.Errorf("r.connection.Query: %v", err)
Ошибки лучше раскрывать, хорошая практика fmt.Errorf("failed to <тут описание>: %v", err)
Тут можно: 
```
return nil, fmt.Errorf("failed to get permission: %v", err)
```
Это позволит в случае ошибки конкретно понять где ошибка (r.connection.Query - может много где использоваться в репозитории)

2024-11-14 23:38 UTC, alexseipopov commented on internal/rpc/service.go
> +		return nil, fmt.Errorf("s.dbR.GetPermissions %v", err)
коммент из репозитория касается всех Errorf

2024-11-16 14:41 UTC, njohanne approved these changes

2024-11-16 19:46 UTC, alexseipopov approved these changes

2024-11-16 19:53 UTC, merged